"""Vạn Vật — Hành Kim (CORE + EXPANDED)"""

# CORE: 5 giác quan, đồ vật theo 12 tầng, con người, bệnh, thú, cây
CORE = {   'benh_tat': {   'chung': 'Bệnh PHỔI, đường hô hấp, DA, xương, răng',
                    'cu_the': [   'Viêm phổi',
                                  'Hen suyễn',
                                  'Viêm phế quản',
                                  'Viêm da',
                                  'Dị ứng da',
                                  'Gãy xương',
                                  'Đau răng',
                                  'Viêm xoang',
                                  'Cảm cúm',
                                  'Covid',
                                  'Lao phổi',
                                  'Ho kéo dài',
                                  'Ung thư phổi',
                                  'Viêm họng',
                                  'Sỏi thận (kim loại/canxi)'],
                    'vi_tri': 'Phổi, phế quản, da, ruột già, mũi, xương'},
    'chat_lieu': 'Kim loại (sắt, thép, đồng, nhôm, vàng, bạc, inox)',
    'con_nguoi': {   'Bệnh': 'Người bệnh phổi/da, ho, khó thở, sụt cân, xanh xao',
                     'Dưỡng': 'Em bé nhỏ, người được chăm sóc, học sinh, người mới vào nghề, thực tập sinh',
                     'Lâm Quan': 'Người có chức vụ, khá giả, gọn gàng, chuyên nghiệp, quản lý, kỹ sư',
                     'Mộ': 'Người ẩn dật, sống khép kín, không giao tiếp, bí ẩn, giữ bí mật',
                     'Suy': 'Người gầy, da xanh xao, hơi mệt mỏi, thu nhập giảm, đang gặp khó khăn',
                     'Thai': 'Thai nhi, em bé sắp sinh, người sắp bắt đầu sự nghiệp mới',
                     'Tuyệt': 'Người cô đơn, không ai biết, biến mất, vô gia cư, lang thang',
                     'Tử': 'Người rất yếu/sắp mất, xương xẩu, tiều tụy, không có sức sống',
                     'giong_noi': 'Trong trẻo, gọn gàng, dứt khoát, ngắn gọn',
                     'nghe_nghiep': 'Quân đội, công an, bác sĩ phẫu thuật, thợ cơ khí, thợ vàng, IT, tài chính, ngân '
                                    'hàng',
                     'ngoai_hinh': 'Da trắng sáng, mặt vuông/tròn, mũi cao, mắt sáng, tóc thưa hoặc đen bóng',
                     'than_hinh': 'Cao gầy hoặc cân đối, xương to, vai rộng',
                     'tinh_cach': 'Cương quyết, dứt khoát, nghiêm túc, kỷ luật, ít nói',
                     'Đế Vượng': 'Lãnh đạo uy quyền, giàu có, da trắng, dáng cao, ăn mặc sang trọng, đeo vàng/kim '
                                 'cương, CEO, tướng quân'},
    'do_vat': {   'Bệnh': [   'Máy hỏng',
                              'Kim gỉ',
                              'Xe máy chết máy',
                              'Đồng hồ chạy sai',
                              'Laptop lỗi màn hình',
                              'Quạt kêu to',
                              'Ống nước rò rỉ'],
                  'Dưỡng': [   'Dao đang rèn',
                               'Kim loại đang đúc',
                               'Trang sức đang chế tác',
                               'Máy đang lắp ráp',
                               'Xe đang sản xuất'],
                  'Lâm Quan': [   'Xe máy',
                                  'Điện thoại iPhone',
                                  'Laptop',
                                  'Dao bếp tốt',
                                  'Nhẫn vàng',
                                  'Kéo chuyên dụng',
                                  'Kìm, búa, cờ lê',
                                  'Ổ khóa mới'],
                  'Mộ': [   'Đồng xu cổ',
                            'Kiếm cổ trong hộp',
                            'Trang sức gia truyền',
                            'Chìa khóa bí ẩn',
                            'Két sắt khóa',
                            'Vàng chôn',
                            'Kho vũ khí'],
                  'Mộc Dục': [   'Dao đã mài lại',
                                 'Chìa khóa cũ đánh bóng',
                                 'Xe đạp sửa xong',
                                 'Nồi niêu rửa sạch',
                                 'Điện thoại reset'],
                  'Quan Đới': [   'Chìa khóa mới',
                                  'Kéo văn phòng',
                                  'Đinh ốc mới',
                                  'Thìa dĩa mới',
                                  'Kim khâu',
                                  'Ghim bấm',
                                  'Kẹp giấy',
                                  'Nồi inox mới'],
                  'Suy': [   'Dao cùn',
                             'Chìa khóa cũ',
                             'Xe đạp hoen rỉ',
                             'Nồi cũ',
                             'Kéo cùn',
                             'Ổ khóa kẹt',
                             'Điện thoại lag',
                             'Vòng tay bạc xỉn'],
                  'Thai': ['Quặng mỏ', 'Kim loại thô', 'Thiết kế dao mới', 'Bản vẽ máy', 'Ý tưởng công nghệ'],
                  'Trường Sinh': [   'Đinh nhỏ mới',
                                     'Kim châm cứu',
                                     'Dây thép mới',
                                     'Chiếc nhẫn nhỏ',
                                     'Ghim cài áo',
                                     'Cúc áo kim loại',
                                     'Khuy đồng'],
                  'Tuyệt': ['Mạt sắt', 'Bụi kim loại', 'Vụn dao', 'Gỉ sét', 'Xỉ hàn', 'Tro kim loại', 'Bức xạ'],
                  'Tử': [   'Sắt vụn',
                            'Kim loại phế liệu',
                            'Xe nát',
                            'Máy bỏ',
                            'Dao gãy',
                            'Kéo gãy',
                            'Điện thoại chết hẳn',
                            'Bình gas rỗng'],
                  'Đế Vượng': [   'Xe hơi hạng sang',
                                  'Tủ sắt ngân hàng',
                                  'Cần cẩu',
                                  'Máy bay',
                                  'Dao kiếm bảo vật',
                                  'Đồng hồ Rolex',
                                  'Trang sức vàng ròng',
                                  'Két sắt lớn']},
    'dong_vat': {   'Mộ': 'Chuột (sống trong hang), rắn (ẩn dưới đất) — ẩn nấp',
                    'Suy': 'Mèo lười, gà già, chim non — yếu ớt',
                    'Tử': 'Xương động vật, da thú khô, nhện — liên quan cái chết',
                    'chung': 'Hổ, báo, ngựa, gà, khỉ, chim ưng, đại bàng',
                    'Đế Vượng': 'Hổ lớn, sư tử, đại bàng, ngựa chiến — mạnh mẽ, hung dữ'},
    'gio': 'Thân-Dậu (15h-19h)',
    'hanh': 'Kim',
    'hinh_dang': 'Tròn, cong, lõm, vòng cung, hình cầu',
    'huong': 'Tây',
    'khuu_giac': {   'mui': 'Không mùi hoặc mùi kim loại tanh nhẹ, mùi sắt',
                     'mui_dac_trung': 'Mùi đồng xu, mùi chìa khóa, mùi thép'},
    'mau_sac': 'Trắng, bạc, vàng kim, xám bạc, ánh kim',
    'mua': 'Thu',
    'ngay': 'Thứ 6 (Kim nhật)',
    'nha_cua': {   'Mộ': 'Nhà kho khóa kín, két sắt, phòng bí mật, hầm',
                   'Suy': 'Nhà cũ có mái tôn rỉ, cửa sắt kẹt, lan can lung lay',
                   'chung': 'Nhà có nhiều kim loại, cửa sắt, lan can inox, mái tôn',
                   'Đế Vượng': 'Biệt thự mái tôn sang trọng, nhà kho lớn, xưởng cơ khí lớn, ngân hàng'},
    'thi_giac': {   'anh_sang': 'Phản chiếu mạnh, lấp lánh, có ánh kim',
                    'be_mat': 'Bóng loáng, nhẵn mịn, hoặc có cạnh sắc',
                    'do_trong': 'Có thể phản chiếu hình ảnh',
                    'mau': 'Trắng sáng, bạc lấp lánh, vàng ánh kim, chrome'},
    'thinh_giac': {   'am_thanh': 'Leng keng, lanh canh, tiếng kim loại va chạm',
                      'giong_noi': 'Trong trẻo, vang, dứt khoát, gọn gàng',
                      'nhac_cu': 'Chuông, chũm chọe, kèn đồng, phong linh'},
    'thuc_vat': {   'Suy': 'Cây héo, lá vàng, cành khô — yếu ớt',
                    'chung': 'Cây có gai, cây cứng, lá nhọn, cây bonsai, cây xương rồng',
                    'Đế Vượng': 'Cây tùng bách đại thụ, cây bonsai quý, lan quý — cao giá'},
    'tinh_chat': 'Cứng, sắc bén, sáng bóng, lạnh, trong trẻo',
    'vi_giac': {'thuc_pham': 'Hành, tỏi, gừng, ớt, rau thơm mùi mạnh', 'vi': 'Cay nồng, hăng (hành tỏi, gừng, ớt)'},
    'xuc_giac': {   'be_mat': 'Nhẵn bóng hoặc có gờ sắc',
                    'cam_giac': 'Lạnh, cứng, trơn, sắc cạnh',
                    'nhiet_do': 'Lạnh khi chạm, dẫn nhiệt nhanh',
                    'trong_luong': 'Nặng so với kích thước'}}

# EXPANDED: Phương tiện, Trang phục, Thực phẩm, Khoáng sản, Công nghệ...
EXPANDED = {   'bo_phan_co_the': [   'Phổi',
                          'Ruột già',
                          'Da',
                          'Xương',
                          'Răng',
                          'Mũi',
                          'Lông/tóc',
                          'Móng tay',
                          'Cột sống',
                          'Sụn',
                          'Thanh quản'],
    'cam_xuc': [   'Buồn',
                   'Đau đớn',
                   'Nghiêm khắc',
                   'Cô đơn',
                   'Kiên cường',
                   'Dứt khoát',
                   'Lạnh lùng',
                   'Tàn nhẫn',
                   'Công bằng',
                   'Chính trực'],
    'cong_nghe': {   'Suy': ['Điện thoại đời cũ', 'Laptop 2010', 'Máy tính bàn cũ', 'iPod cũ'],
                     'Tử': ['Điện thoại chết', 'Laptop hỏng main', 'Ổ cứng bad sector'],
                     'chung': [   'iPhone',
                                  'MacBook',
                                  'iPad',
                                  'Apple Watch',
                                  'AirPods',
                                  'Samsung Galaxy',
                                  'Laptop Dell',
                                  'PC Gaming',
                                  'Máy in laser',
                                  'Loa bluetooth',
                                  'TV OLED',
                                  'Máy ảnh Canon',
                                  'Drone',
                                  'Robot hút bụi',
                                  'Ổ cứng SSD',
                                  'USB flash',
                                  'Tai nghe',
                                  'Sạc không dây'],
                     'Đế Vượng': ['Server IBM', 'Siêu máy tính', 'Vệ tinh', 'Máy MRI', 'Robot công nghiệp']},
    'cong_nghiep': [   'Cần cẩu',
                       'Máy tiện',
                       'Máy phay',
                       'Máy ép',
                       'Máy cắt laser',
                       'Dây chuyền sản xuất',
                       'Lò luyện thép',
                       'Máy hàn',
                       'Máy nén khí',
                       'Ống dẫn',
                       'Van công nghiệp',
                       'Bình gas',
                       'Thang máy'],
    'dia_ly': [   'Mỏ vàng',
                  'Mỏ bạc',
                  'Mỏ sắt',
                  'Núi đá vôi',
                  'Sa mạc (cát kim loại)',
                  'Khu công nghiệp',
                  'Nhà máy',
                  'Ngân hàng',
                  'Sở giao dịch chứng khoán'],
    'gia_dung': [   'Nồi',
                    'Chảo',
                    'Dao bếp',
                    'Thìa',
                    'Dĩa',
                    'Mở nắp chai',
                    'Nhíp',
                    'Bấm móng tay',
                    'Cạo râu',
                    'Muỗng canh',
                    'Vá múc',
                    'Máy xay sinh tố (lưỡi)',
                    'Máy ép trái cây',
                    'Ấm siêu tốc (inox)',
                    'Bình giữ nhiệt',
                    'Khay inox',
                    'Rổ rá inox',
                    'Kệ gia vị'],
    'khoang_san': [   'Vàng',
                      'Bạc',
                      'Bạch kim',
                      'Đồng',
                      'Sắt',
                      'Nhôm',
                      'Niken',
                      'Thiếc',
                      'Kẽm',
                      'Titan',
                      'Crom',
                      'Molypden',
                      'Tungsten',
                      'Kim cương',
                      'Sapphire trắng',
                      'Ngọc trai',
                      'Thạch anh trắng'],
    'ky_thuat_so': [   'Bitcoin',
                       'Cryptocurrency',
                       'Blockchain',
                       'Fintech',
                       'NFT vàng',
                       'App ngân hàng',
                       'Ví điện tử',
                       'Thanh toán contactless'],
    'nghe_thuat': [   'Tranh đồng đúc',
                      'Tượng inox',
                      'Sculpture kim loại',
                      'Jewelry art',
                      'Chạm khắc bạc',
                      'Đúc đồng nghệ thuật',
                      'Khắc laser trên kim loại'],
    'nhac_cu': [   'Chuông đồng',
                   'Phong linh',
                   'Kèn đồng (trumpet)',
                   'Kèn trombone',
                   'Cymbal',
                   'Chiêng',
                   'Thanh la',
                   'Xylophone kim loại',
                   'Harmonica',
                   'Kèn sáo kim loại',
                   'Tam giác (triangle)'],
    'noi_that': [   'Kệ inox',
                    'Giá treo quần áo kim loại',
                    'Gương khung bạc',
                    'Đèn chùm pha lê',
                    'Bàn kính khung sắt',
                    'Ghế xoay kim loại',
                    'Tủ sắt hồ sơ',
                    'Kệ giày inox',
                    'Móc treo tường',
                    'Rèm cửa kim tuyến',
                    'Bệ lavabo inox',
                    'Vòi sen inox'],
    'nong_nghiep': [   'Liềm',
                       'Cuốc sắt',
                       'Xẻng sắt',
                       'Dao phát cỏ',
                       'Cày sắt',
                       'Bừa',
                       'Máy gặt liên hợp',
                       'Máy cày',
                       'Hệ thống tưới phun'],
    'phuong_tien': {   'Lâm Quan': ['Toyota Camry', 'Honda CR-V', 'BMW 3 series', 'Xe tải Hyundai'],
                       'Suy': ['Xe cũ hoen rỉ', 'Xe máy cà tàng', 'Xe đạp rỉ sét'],
                       'Tử': ['Xe phế liệu', 'Ô tô bị đập', 'Xe tai nạn nát'],
                       'chung': [   'Xe hơi',
                                    'Xe máy',
                                    'Xe đạp',
                                    'Tàu hỏa',
                                    'Máy bay',
                                    'Tàu ngầm',
                                    'Xe tăng',
                                    'Xe bọc thép'],
                       'Đế Vượng': ['Rolls Royce', 'Lamborghini', 'Private jet', 'Xe Maybach', 'Du thuyền kim loại']},
    'quoc_gia': [   'Phương Tây',
                    'Châu Âu',
                    'Mỹ',
                    'Anh',
                    'Đức',
                    'Nhật Bản (công nghệ)',
                    'Hàn Quốc (Samsung)',
                    'Thụy Sĩ (đồng hồ)',
                    'Ý (siêu xe)'],
    'the_thao': [   'Tạ',
                    'Barbell',
                    'Dumbbell',
                    'Xe đạp racing',
                    'Kiếm fencing',
                    'Cung tên thể thao',
                    'Gậy golf kim loại',
                    'Patin ice'],
    'thoi_tiet': ['Sương giá', 'Băng tuyết', 'Gió lạnh', 'Mưa đá', 'Không khí khô hanh', 'Gió thu se lạnh', 'Khí lạnh'],
    'thuc_pham_chi_tiet': {   'chung': [   'Hành tây',
                                           'Tỏi',
                                           'Gừng',
                                           'Ớt',
                                           'Tiêu',
                                           'Quế',
                                           'Hồi',
                                           'Rau mùi',
                                           'Wasabi',
                                           'Mustard',
                                           'Sả',
                                           'Riềng',
                                           'Nghệ',
                                           'Bạc hà',
                                           'Thịt gà',
                                           'Phổi bò',
                                           'Thịt trắng',
                                           'Cơm cháy giòn'],
                              'do_uong': ['Rượu trắng', 'Sake', 'Vodka', 'Soju', 'Nước suối', 'Trà trắng']},
    'ton_giao': [   'Chuông chùa/nhà thờ',
                    'Thánh giá bạc/vàng',
                    'Lư hương đồng',
                    'Kiếm phát ấn',
                    'Chén thánh',
                    'Gương phong thủy bát quái',
                    'Tượng Phật đồng',
                    'Chuông gió phong thủy',
                    'La bàn/Kinh Dịch'],
    'trang_phuc': {   'Mộ': ['Áo giáp cổ', 'Trang sức gia truyền', 'Huy chương cũ trong hộp'],
                      'Suy': ['Dây chuyền bạc xỉn', 'Đồng hồ cũ chạy sai', 'Kính gãy gọng'],
                      'chung': [   'Áo giáp',
                                   'Dây chuyền bạc',
                                   'Đồng hồ kim loại',
                                   'Kính gọng kim loại',
                                   'Thắt lưng khóa',
                                   'Giày da bóng',
                                   'Nón bảo hiểm',
                                   'Áo khoác da'],
                      'Đế Vượng': [   'Bộ vest Armani',
                                      'Đồng hồ Patek Philippe',
                                      'Nhẫn kim cương 5 carat',
                                      'Vương miện vàng',
                                      'Áo giáp bạch kim',
                                      'Kính Cartier vàng']},
    'van_phong': [   'Ghim',
                     'Kẹp giấy',
                     'Dao rọc giấy',
                     'Kéo văn phòng',
                     'Máy dập ghim',
                     'Khóa tủ hồ sơ',
                     'Bấm lỗ',
                     'Thước kẻ kim loại',
                     'Sọt rác inox'],
    'vu_khi': [   'Kiếm',
                  'Dao',
                  'Rìu',
                  'Búa chiến',
                  'Giáo',
                  'Mác',
                  'Súng',
                  'Đạn',
                  'Tên lửa',
                  'Bom',
                  'Lựu đạn',
                  'Pháo',
                  'Tàu chiến',
                  'Xe tăng',
                  'Khiên',
                  'Giáp',
                  'Nỏ',
                  'Cung tên'],
    'y_te': [   'Dao mổ',
                'Kim tiêm',
                'Kéo phẫu thuật',
                'Kẹp y tế',
                'Nẹp xương',
                'Máy MRI',
                'Máy X-quang',
                'Stent tim',
                'Implant titan',
                'Răng giả kim loại',
                'Ống nghe y tế',
                'Nhiệt kế thủy ngân',
                'Xe lăn (khung sắt)',
                'Nạng inox',
                'Thuốc viên nén',
                'Thuốc bọc vỏ nhôm',
                'Bình oxy',
                'Máy thở']}
