"""Vạn Vật — Hành Mộc (CORE + EXPANDED)"""

# CORE: 5 giác quan, đồ vật theo 12 tầng, con người, bệnh, thú, cây
CORE = {   'benh_tat': {   'chung': 'Bệnh GAN, MẬT, MẮT, gân cốt, chân tay',
                    'cu_the': [   'Viêm gan A/B/C',
                                  'Xơ gan',
                                  'Sỏi mật',
                                  'Cận thị',
                                  'Đau mắt đỏ',
                                  'Thoát vị đĩa đệm',
                                  'Đau lưng',
                                  'Co cơ',
                                  'Gout',
                                  'Trầm cảm',
                                  'Stress',
                                  'Mất ngủ',
                                  'Động kinh',
                                  'Tay chân tê bì',
                                  'Viêm khớp'],
                    'vi_tri': 'Gan, mật, mắt, gân, cơ, đầu gối, vai gáy'},
    'chat_lieu': 'Gỗ, tre, nứa, mây, giấy, vải bông, cao su, nhựa (từ cây)',
    'con_nguoi': {   'Bệnh': 'Người bệnh gan, đau mắt, co giật, tay chân tê — xanh xao, yếu ớt',
                     'Dưỡng': 'Em bé tập đi, học sinh tiểu học, nhà văn tập sự, thợ học việc',
                     'Lâm Quan': 'Giáo viên giỏi, thợ mộc lành nghề, nhà thiết kế — cần cù, chuyên nghiệp',
                     'Mộ': 'Nhà sư, người ẩn cư trong rừng, thầy phong thủy sống biệt lập',
                     'Suy': 'Người làm vườn mệt mỏi, giáo viên stress, thợ mộc thu nhập giảm — gầy, mắt thâm',
                     'Thai': 'Thai nhi, em bé sắp sinh, sinh viên sắp ra trường',
                     'Tuyệt': 'Vô gia cư sống ngoài trời, người bị bỏ rơi, mất tích trong rừng',
                     'Tử': 'Người kiệt sức, da vàng bệnh gan, rất gầy, không còn sức sống',
                     'giong_noi': 'Trầm ấm, nhẹ nhàng, dễ nghe, uyển chuyển',
                     'nghe_nghiep': 'Giáo viên, nhà văn, họa sĩ, nhà thiết kế, bác sĩ Đông y, thợ mộc, nông dân, kiến '
                                    'trúc sư',
                     'ngoai_hinh': 'Da ngăm/nâu sáng, dáng cao gầy, mắt dài, tay chân dài, tóc dày',
                     'than_hinh': 'Cao, gầy, thanh mảnh, linh hoạt, dẻo dai',
                     'tinh_cach': 'Nhân hậu, từ bi, yêu thiên nhiên, sáng tạo, kiên nhẫn',
                     'Đế Vượng': 'Giáo sư nổi tiếng, nhà văn uy tín, CEO ngành gỗ/nội thất, kiến trúc sư lớn — cao '
                                 'gầy, da sáng, ăn mặc thanh lịch'},
    'do_vat': {   'Bệnh': ['Gỗ mối mọt', 'Sách ẩm mốc', 'Quần áo rách', 'Cây bị sâu', 'Bút hết mực'],
                  'Dưỡng': ['Cây mới trồng', 'Sách đang viết', 'Quần áo đang may', 'Bàn đang đóng'],
                  'Lâm Quan': [   'Bàn làm việc gỗ',
                                  'Ghế sofa vải',
                                  'Sách vở',
                                  'Cây cảnh lớn',
                                  'Bút vẽ',
                                  'Khung tranh',
                                  'Tủ quần áo'],
                  'Mộ': ['Sách cổ trong rương', 'Gỗ trầm chôn', 'Quần áo cất kỹ', 'Hạt giống giữ', 'Bản thảo cũ'],
                  'Mộc Dục': ['Thớt gỗ rửa xong', 'Quần áo giặt xong', 'Sách cũ lau sạch', 'Cây tưới xong'],
                  'Quan Đới': ['Bút mới', 'Tập vở mới', 'Quần áo mới', 'Giấy A4', 'Hoa tươi', 'Khăn mới'],
                  'Suy': ['Bàn gỗ cũ', 'Sách cũ ố vàng', 'Quần áo cũ', 'Dép cũ', 'Ghế lung lay', 'Cây héo'],
                  'Thai': ['Hạt giống chưa nảy mầm', 'Ý tưởng viết sách', 'Bản thiết kế nội thất', 'Phôi gỗ'],
                  'Trường Sinh': ['Hạt giống', 'Cây con', 'Giấy gấp', 'Bút chì nhỏ', 'Lá thư', 'Bookmark'],
                  'Tuyệt': ['Mùn gỗ', 'Tro giấy', 'Bụi vải', 'Rác thực vật', 'Phân bón hữu cơ'],
                  'Tử': ['Gỗ mục', 'Giấy nát', 'Vải rách nát', 'Cây chết khô', 'Bút gãy', 'Dép đứt'],
                  'Đế Vượng': [   'Bàn gỗ gụ/lim đại',
                                  'Tủ sách gỗ quý',
                                  'Cây đại thụ',
                                  'Thuyền gỗ lớn',
                                  'Đàn piano grand',
                                  'Giường ngủ king size gỗ']},
    'dong_vat': {   'Suy': 'Chim non, thỏ yếu, sâu bọ — nhỏ bé',
                    'Tử': 'Gỗ lũa (cây chết), cành khô, xác lá',
                    'chung': 'Thỏ, mèo, chim, bướm, sâu, côn trùng, rắn non',
                    'Đế Vượng': 'Rồng (biểu tượng), đại bàng, ngựa chiến — mạnh mẽ phi thường'},
    'gio': 'Dần-Mão (3h-7h)',
    'hanh': 'Mộc',
    'hinh_dang': 'Dài, thẳng, hình trụ, hình chữ nhật, thanh mảnh',
    'huong': 'Đông',
    'khuu_giac': {   'mui': 'Mùi gỗ thơm, mùi cây xanh, mùi lá tươi, mùi đất',
                     'mui_dac_trung': 'Mùi trầm hương, mùi gỗ thông, mùi tre, mùi giấy mới'},
    'mau_sac': 'Xanh lá, xanh ngọc, xanh lục, nâu gỗ, be',
    'mua': 'Xuân',
    'ngay': 'Thứ 5 (Mộc nhật)',
    'nha_cua': {   'Mộ': 'Nhà trong rừng, cabin gỗ biệt lập, nhà kho gỗ cũ',
                   'Suy': 'Nhà gỗ cũ mục nát, sàn gỗ kêu, cửa gỗ mối ăn',
                   'chung': 'Nhà gỗ, nhà sàn, nhà có nhiều cây xanh, ban công trồng cây',
                   'Đế Vượng': 'Biệt thự gỗ cao cấp, nhà vườn rộng, khu resort sinh thái'},
    'thi_giac': {   'anh_sang': 'Ánh sáng mềm, tự nhiên, xanh mát',
                    'be_mat': 'Có vân gỗ, sớ vải, kết cấu tự nhiên',
                    'do_trong': 'Mờ đục, có sớ, có vân',
                    'mau': 'Xanh lá tươi, xanh đậm, nâu gỗ, nâu nhạt'},
    'thinh_giac': {   'am_thanh': 'Tiếng kẽo kẹt, tiếng lá xào xạc, tiếng gỗ gõ',
                      'giong_noi': 'Ấm áp, nhẹ nhàng, trầm ấm, uyển chuyển',
                      'nhac_cu': 'Đàn guitar, đàn tranh, sáo trúc, mõ gỗ'},
    'thuc_vat': {   'Suy': 'Cây cúc tàn, hoa héo, cỏ úa — sắp tàn',
                    'chung': 'Tre, trúc, tùng, bách, sen, lan, hoa hồng',
                    'Đế Vượng': 'Đại thụ, cây đa, cây sanh, cổ thụ ngàn năm — vĩ đại'},
    'tinh_chat': 'Mềm dẻo, có sức sống, phát triển, linh hoạt',
    'vi_giac': {   'thuc_pham': 'Rau xanh, trái cây, đậu, ngũ cốc, cơm, mì',
                   'vi': 'Chua (chanh, me, giấm, trái cây chua)'},
    'xuc_giac': {   'be_mat': 'Thô ráp tự nhiên, có vân, có sớ',
                    'cam_giac': 'Ấm nhẹ, mềm nhưng dai, co giãn, linh hoạt',
                    'nhiet_do': 'Ấm tự nhiên, không lạnh',
                    'trong_luong': 'Nhẹ đến trung bình'}}

# EXPANDED: Phương tiện, Trang phục, Thực phẩm, Khoáng sản, Công nghệ...
EXPANDED = {   'bo_phan_co_the': [   'Gan',
                          'Mật',
                          'Mắt',
                          'Gân',
                          'Cơ bắp',
                          'Ngón tay',
                          'Ngón chân',
                          'Đầu gối',
                          'Vai',
                          'Cánh tay',
                          'Cẳng chân',
                          'Móng tay (keratin)'],
    'cam_xuc': [   'Nhân ái',
                   'Từ bi',
                   'Sáng tạo',
                   'Kiên nhẫn',
                   'Dễ thương',
                   'Mơ mộng',
                   'Hay giận (Can nộ)',
                   'Tự do',
                   'Phóng khoáng'],
    'cong_nghe': {   'chung': [   'Máy tính bằng gỗ (DIY)',
                                  'Ốp lưng gỗ',
                                  'Bàn phím cơ gỗ',
                                  'Loa gỗ',
                                  'Tai nghe vỏ gỗ',
                                  'Giá đỡ laptop gỗ']},
    'cong_nghiep': [   'Xưởng gỗ',
                       'Máy cưa',
                       'Máy bào',
                       'Máy khoan gỗ',
                       'Lò sấy gỗ',
                       'Xưởng giấy',
                       'Nhà máy dệt',
                       'Xưởng may',
                       'Nhà in'],
    'dia_ly': [   'Rừng',
                  'Vườn',
                  'Công viên',
                  'Đồng lúa',
                  'Nương rẫy',
                  'Rừng nhiệt đới',
                  'Rừng thông',
                  'Rừng tre',
                  'Đồi chè',
                  'Vườn hoa',
                  'Nhà kính trồng cây'],
    'do_tre_em': [   'Xích đu gỗ',
                     'Khối gỗ xếp hình',
                     'Búp bê vải',
                     'Cầu trượt gỗ',
                     'Xe gỗ đồ chơi',
                     'Bảng chữ cái gỗ',
                     'Xếp hình gỗ Montessori'],
    'gia_dung': [   'Thớt gỗ',
                    'Đũa tre',
                    'Muỗng gỗ',
                    'Rổ mây',
                    'Giỏ tre',
                    'Hộp gỗ đựng trà',
                    'Giá đỡ nồi tre',
                    'Lót nồi tre',
                    'Khay trà gỗ',
                    'Chổi que',
                    'Cây lau nhà',
                    'Thùng gỗ',
                    'Giỏ đi chợ mây tre'],
    'khoang_san': [   'Ngọc bích (jade)',
                      'Emerald (ngọc lục bảo)',
                      'Malachite',
                      'Peridot',
                      'Tourmaline xanh',
                      'Aventurine',
                      'Hổ phách (amber)'],
    'ky_thuat_so': [   'Ebook',
                       'Blog',
                       'Website tin tức',
                       'App đọc sách',
                       'Podcast giáo dục',
                       'Khóa học online',
                       'Notion',
                       'Google Docs',
                       'App trồng cây ảo'],
    'my_pham': [   'Serum thiên nhiên',
                   'Kem dưỡng hữu cơ',
                   'Son môi thảo dược',
                   'Dầu dừa',
                   'Dầu argan',
                   'Tinh dầu tràm trà',
                   'Mặt nạ lá neem',
                   'Xà phòng handmade',
                   'Bột nghệ',
                   'Nước hoa hồng'],
    'nghe_thuat': [   'Tranh thủy mặc',
                      'Thư pháp',
                      'Điêu khắc gỗ',
                      'Tranh lụa',
                      'Tranh giấy dó',
                      'Origami',
                      'Ikebana (cắm hoa)',
                      'Bonsai nghệ thuật'],
    'nhac_cu': [   'Guitar acoustic',
                   'Guitar classic',
                   'Ukulele',
                   'Đàn tranh',
                   'Đàn bầu',
                   'Sáo trúc',
                   'Tiêu',
                   'Đàn nhị',
                   'Piano (thân gỗ)',
                   'Violin (gỗ)',
                   'Cello',
                   'Đàn tỳ bà',
                   'Mõ gỗ',
                   'Castanets gỗ',
                   'Maracas gỗ',
                   'Đàn tam thập lục',
                   'Đàn nguyệt',
                   'Kèn oboe (thân gỗ)'],
    'noi_that': [   'Bàn gỗ',
                    'Ghế gỗ',
                    'Tủ gỗ',
                    'Kệ sách gỗ',
                    'Khung ảnh gỗ',
                    'Rèm vải cotton',
                    'Thảm cói',
                    'Chiếu tre',
                    'Gối bông',
                    'Chăn len',
                    'Đệm cao su',
                    'Ghế mây',
                    'Bàn tre',
                    'Giá sách tre',
                    'Bình hoa gỗ'],
    'nong_nghiep': [   'Cuốc gỗ',
                       'Cày gỗ',
                       'Rổ tre',
                       'Gánh tre',
                       'Thúng mủng',
                       'Hạt giống',
                       'Phân bón hữu cơ',
                       'Máy xay lúa gỗ',
                       'Bồ đựng thóc',
                       'Nong nia',
                       'Quang gánh',
                       'Đòn gánh',
                       'Liếp tre'],
    'phuong_tien': {   'Lâm Quan': ['Thuyền câu gỗ', 'Xe đạp tre', 'Cáng tre'],
                       'Suy': ['Thuyền cũ', 'Xe gỗ lung lay', 'Xuồng hỏng'],
                       'chung': ['Thuyền gỗ', 'Xe kéo gỗ', 'Xe ngựa', 'Xe bò', 'Cáng', 'Thang gỗ', 'Kiệu'],
                       'Đế Vượng': ['Thuyền rồng', 'Du thuyền gỗ teak', 'Tàu buồm cổ']},
    'quoc_gia': [   'Phương Đông',
                    'Việt Nam (tre, lúa)',
                    'Trung Quốc (trà, gỗ)',
                    'Nhật Bản (tre/bonsai)',
                    'Indonesia (gỗ teak)',
                    'Brazil (nhiệt đới)'],
    'the_thao': [   'Gậy cricket (gỗ)',
                    'Gậy bóng chày (gỗ)',
                    'Bàn bóng bàn',
                    'Ván lướt sóng gỗ',
                    'Cung tre',
                    'Kiếm kendo gỗ (bokken)',
                    'Thảm yoga (cotton)',
                    'Dây thừng leo núi'],
    'thoi_tiet': [   'Gió xuân',
                     'Mưa phùn',
                     'Sấm sét (sét đánh cây)',
                     'Bão lớn (cây đổ)',
                     'Thời tiết ấm áp',
                     'Mùa xuân hoa nở'],
    'thuc_pham_chi_tiet': {   'chung': [   'Rau muống',
                                           'Rau cải',
                                           'Rau xà lách',
                                           'Bắp cải',
                                           'Bí xanh',
                                           'Mướp',
                                           'Khổ qua',
                                           'Cà chua',
                                           'Dưa chuột',
                                           'Đậu que',
                                           'Ngô',
                                           'Khoai mì',
                                           'Chuối',
                                           'Cam',
                                           'Bưởi',
                                           'Chanh',
                                           'Me',
                                           'Xoài',
                                           'Ổi',
                                           'Táo',
                                           'Nho',
                                           'Lê',
                                           'Đào',
                                           'Mận',
                                           'Hồng',
                                           'Dừa',
                                           'Sầu riêng',
                                           'Chôm chôm',
                                           'Gạo',
                                           'Lúa mì',
                                           'Yến mạch',
                                           'Đậu nành',
                                           'Đậu xanh',
                                           'Đậu phộng',
                                           'Mè',
                                           'Hạt điều',
                                           'Hạt óc chó',
                                           'Hạnh nhân',
                                           'Macca',
                                           'Thịt bò (gan bò)',
                                           'Mộc nhĩ',
                                           'Nấm hương',
                                           'Đậu hủ',
                                           'Tempeh'],
                              'do_uong': [   'Nước mía',
                                             'Nước dừa',
                                             'Sinh tố',
                                             'Nước ép trái cây',
                                             'Trà xanh',
                                             'Trà hoa cúc',
                                             'Rượu trái cây',
                                             'Kombucha']},
    'ton_giao': [   'Kinh sách',
                    'Tràng hạt gỗ',
                    'Mõ gỗ',
                    'Bàn thờ gỗ',
                    'Bài vị gỗ',
                    'Tượng gỗ',
                    'Hương trầm',
                    'Giấy sớ',
                    'Nón lá tu hành',
                    'Áo cà sa vải'],
    'trang_phuc': {   'Mộ': ['Áo xưa cất kỹ', 'Áo gia truyền', 'Trang phục lễ hội cổ'],
                      'Suy': ['Áo cũ sờn', 'Quần vải bạc', 'Giày vải rách', 'Khăn cũ'],
                      'chung': [   'Áo bông',
                                   'Áo lụa',
                                   'Áo len',
                                   'Quần vải',
                                   'Váy cotton',
                                   'Giày vải',
                                   'Nón lá',
                                   'Khăn quàng vải',
                                   'Áo dài',
                                   'Kimono',
                                   'Hanbok'],
                      'Đế Vượng': [   'Áo dài gấm lụa',
                                      'Kimono tơ tằm',
                                      'Áo lông thú quý',
                                      'Váy haute couture vải tự nhiên']},
    'van_phong': [   'Bút chì',
                     'Bút mực',
                     'Tập vở',
                     'Sổ tay',
                     'Phong bì',
                     'Giấy note',
                     'Thước gỗ',
                     'Hồ dán',
                     'Băng keo giấy',
                     'Bìa hồ sơ',
                     'File đựng tài liệu'],
    'y_te': [   'Thuốc thảo dược',
                'Thuốc Đông y',
                'Châm cứu (cây kim nhưng kỹ thuật Mộc)',
                'Xoa bóp bấm huyệt',
                'Yoga',
                'Thiền',
                'Mát-xa',
                'Bó thuốc nam',
                'Dầu gió',
                'Cao dán',
                'Viên uống vitamin tự nhiên',
                'Probiotic',
                'Thực phẩm chức năng hữu cơ',
                'Trà thảo dược',
                'Tinh dầu chữa bệnh']}
