"""Vạn Vật — Hành Thủy (CORE + EXPANDED)"""

# CORE: 5 giác quan, đồ vật theo 12 tầng, con người, bệnh, thú, cây
CORE = {   'benh_tat': {   'chung': 'Bệnh THẬN, BÀNG QUANG, sinh dục, tai, xương tuỷ, máu',
                    'cu_the': [   'Suy thận',
                                  'Sỏi thận',
                                  'Viêm bàng quang',
                                  'Tiểu đường',
                                  'Bệnh lậu',
                                  'Bệnh thận',
                                  'Phù nề',
                                  'Cao huyết áp',
                                  'Thiếu máu',
                                  'Bệnh tai',
                                  'Điếc',
                                  'Tiểu tiện bất thường',
                                  'Xuất huyết',
                                  'Bạch cầu bất thường'],
                    'vi_tri': 'Thận, bàng quang, tai, xương tủy, tử cung, tiền liệt'},
    'chat_lieu': 'Nước, thủy tinh, pha lê, nhựa trong, mực, dầu, xăng',
    'con_nguoi': {   'Bệnh': 'Người bệnh thận, phù nề, tiểu đường — mặt sưng, chân phù',
                     'Dưỡng': 'Em bé sơ sinh, người đang phục hồi sức khỏe, uống thuốc',
                     'Lâm Quan': 'Bartender giỏi, kỹ sư thủy lợi, nhà buôn — lanh lợi, xởi lởi',
                     'Mộ': 'Người sống dưới tàu, thợ lặn, người làm việc dưới nước/ngầm',
                     'Suy': 'Người buôn bán ế ẩm, ngư dân nghèo — gầy, da đen nhăm, mệt',
                     'Thai': 'Thai nhi trong bụng mẹ (được nước ối bao bọc)',
                     'Tuyệt': 'Người mất tích trên biển, lưu lạc xa, không liên lạc',
                     'Tử': 'Người đuối nước, nghiện rượu, mất phương hướng — tiều tụy',
                     'giong_noi': 'Nhỏ nhẹ, trôi chảy, lưu loát, nhiều ngôn ngữ',
                     'nghe_nghiep': 'Thủy thủ, ngư dân, pha chế, bartender, nhà ngoại giao, gián điệp, nhà tâm lý, '
                                    'thuỷ lợi, phong thủy',
                     'ngoai_hinh': 'Da đen/ngăm, mặt tròn đầy, mắt to, môi dày, tóc đen nhánh',
                     'than_hinh': 'Mập, tròn trịa, hoặc cao to thuỷ vượng',
                     'tinh_cach': 'Thông minh, lanh lợi, khéo léo, uyển chuyển, hay thay đổi',
                     'Đế Vượng': 'Thương nhân giàu có (buôn bán quốc tế), ngoại giao gia, nhà tâm lý nổi tiếng — đen '
                                 'bóng, mập, ăn nói lưu loát'},
    'do_vat': {   'Bệnh': ['Nước bẩn', 'Nước cống', 'Mực loãng', 'Sơn ướt bong tróc', 'Bồn rò rỉ', 'Nước đá chảy'],
                  'Dưỡng': ['Mưa phùn', 'Sương mai', 'Giọt nước đầu vòi', 'Nước ươm hạt'],
                  'Lâm Quan': [   'Bình nước',
                                  'Máy giặt',
                                  'Bồn tắm',
                                  'Chai rượu',
                                  'Bể cá',
                                  'Nước hoa',
                                  'Máy lọc nước gia đình'],
                  'Mộ': ['Nước ngầm', 'Giếng sâu', 'Bể ngầm', 'Chai rượu chôn', 'Nước khoáng dưới đất', 'Suối ngầm'],
                  'Mộc Dục': ['Nước tắm', 'Xà phòng', 'Dầu gội', 'Nước rửa tay', 'Nước lau sàn'],
                  'Quan Đới': ['Ly nước mới', 'Bình trà', 'Chai nước suối', 'Mực viết', 'Son dưỡng ẩm', 'Kem dưỡng da'],
                  'Suy': ['Nước cũ trong bình', 'Rượu để lâu', 'Kem hết hạn', 'Trà nguội', 'Nước hoa bay mùi'],
                  'Thai': ['Mây (chứa nước)', 'Hơi nước', 'Sương mù', 'Ý tưởng nước hoa mới'],
                  'Trường Sinh': ['Giọt sương', 'Nước mắt', 'Giọt mực nhỏ', 'Bong bóng nước', 'Sữa non'],
                  'Tuyệt': ['Hơi nước bay hơi', 'Sa mạc khô', 'Giếng cạn', 'Sông khô', 'Bụi muối'],
                  'Tử': ['Nước thối', 'Ao tù', 'Mực cạn', 'Bình nước vỡ', 'Nước tiểu', 'Nước bọt khô'],
                  'Đế Vượng': [   'Bể cá koi đại',
                                  'Du thuyền',
                                  'Bể bơi',
                                  'Đài phun nước',
                                  'Chai rượu vang quý',
                                  'Nước hoa Chanel No.5',
                                  'Máy lọc nước công nghiệp']},
    'dong_vat': {   'Suy': 'Cá nhỏ, tôm riu, ốc nhỏ — bé tẹo',
                    'Tử': 'Cá chết, ốc chết — thối rữa',
                    'chung': 'Cá, tôm, cua, ốc, rùa, rắn nước, cá heo, cá voi',
                    'Đế Vượng': 'Cá voi, cá heo, rồng (biểu tượng nước) — khổng lồ'},
    'gio': 'Hợi-Tý (21h-1h)',
    'hanh': 'Thủy',
    'hinh_dang': 'Vô định hình, uốn lượn, gợn sóng, nhấp nhô, giọt',
    'huong': 'Bắc',
    'khuu_giac': {   'mui': 'Mùi nước, mùi biển mặn, mùi mưa, mùi ẩm',
                     'mui_dac_trung': 'Mùi nước hoa, mùi cá biển, mùi rong rêu, mùi ao hồ'},
    'mau_sac': 'Đen, xanh đậm, xanh navy, tím đậm, trong suốt',
    'mua': 'Đông',
    'ngay': 'Thứ 4 (Thủy nhật)',
    'nha_cua': {   'Mộ': 'Nhà dưới tầng hầm, gần giếng, nhà nổi',
                   'Suy': 'Nhà dột, ống nước rò rỉ, bồn cầu hỏng',
                   'chung': 'Nhà gần sông, biển, hồ, nhà có bể cá, đài phun nước',
                   'Đế Vượng': 'Resort ven biển, nhà hàng trên thuyền, biệt thự mặt hồ'},
    'thi_giac': {   'anh_sang': 'Phản chiếu, lấp lánh trên mặt nước, lung linh',
                    'be_mat': 'Bóng ướt, trong suốt, có bọt, gợn sóng',
                    'do_trong': 'Trong suốt đến đục (tùy trạng thái)',
                    'mau': 'Đen sâu, xanh đậm, xanh nước biển, trong suốt'},
    'thinh_giac': {   'am_thanh': 'Tiếng nước chảy, tiếng mưa, tiếng sóng, tí tách',
                      'giong_noi': 'Nhẹ nhàng, êm ái, lưu loát, trôi chảy',
                      'nhac_cu': 'Trống nước, đàn bầu, tiếng suối, tiếng mưa'},
    'thuc_vat': {   'Suy': 'Bèo tấm, rong rêu, tảo xanh — tầm thường',
                    'chung': 'Sen, súng, rong rêu, bèo, tảo, cây thủy sinh',
                    'Đế Vượng': 'Sen hồng nở rộ, cây bồ đề, cây đa ven sông — đẹp'},
    'tinh_chat': 'Lỏng, mềm mại, linh hoạt, thấm nhuần, biến hóa',
    'vi_giac': {   'thuc_pham': 'Nước, trà, cà phê, rượu, bia, sữa, nước mắm, muối, hải sản',
                   'vi': 'Mặn (muối, nước mắm, hải sản)'},
    'xuc_giac': {   'be_mat': 'Trơn ướt, lỏng, không nắm được',
                    'cam_giac': 'Lạnh, ướt, trơn, mềm, mát, lỏng',
                    'nhiet_do': 'Lạnh, mát (trừ nước nóng)',
                    'trong_luong': 'Nhẹ (giọt) đến rất nặng (biển cả)'}}

# EXPANDED: Phương tiện, Trang phục, Thực phẩm, Khoáng sản, Công nghệ...
EXPANDED = {   'bo_phan_co_the': [   'Thận',
                          'Bàng quang',
                          'Tai',
                          'Xương tủy',
                          'Tử cung',
                          'Tinh hoàn',
                          'Tuyến tiền liệt',
                          'Niệu đạo',
                          'Bọng đái',
                          'Máu',
                          'Nước bọt',
                          'Mồ hôi',
                          'Nước mắt',
                          'Dịch não tủy'],
    'cam_xuc': [   'Sợ hãi',
                   'Lo lắng',
                   'Bất an',
                   'Linh hoạt',
                   'Khôn ngoan',
                   'Thâm sâu',
                   'Bí ẩn',
                   'Trầm lặng',
                   'Đa nghi',
                   'Nhạy cảm'],
    'cong_nghe': {   'chung': [   'Máy lọc nước',
                                  'Máy giặt',
                                  'Bình nóng lạnh',
                                  'Máy rửa bát',
                                  'Máy lọc không khí (ẩm)',
                                  'Máy phun sương',
                                  'Máy tạo hơi nước']},
    'cong_nghiep': [   'Nhà máy nước',
                       'Đập thủy điện',
                       'Trạm bơm',
                       'Nhà máy bia',
                       'Nhà máy nước giải khát',
                       'Xưởng nước mắm',
                       'Xưởng đá',
                       'Hệ thống tưới tiêu',
                       'Kênh mương',
                       'Đê đập'],
    'dia_ly': [   'Sông',
                  'Suối',
                  'Hồ',
                  'Biển',
                  'Đại dương',
                  'Ao',
                  'Đầm lầy',
                  'Thác nước',
                  'Sông ngầm',
                  'Mạch nước ngầm',
                  'Vịnh',
                  'Eo biển',
                  'Phá',
                  'Lagoon',
                  'Bắc Cực',
                  'Nam Cực',
                  'Sông Mekong',
                  'Sông Amazon',
                  'Biển Đông'],
    'do_tre_em': [   'Phao bơi',
                     'Súng nước',
                     'Bong bóng xà phòng',
                     'Bể bơi mini',
                     'Vịt cao su',
                     'Đồ chơi tắm',
                     'Cát kinetic'],
    'gia_dung': [   'Bồn rửa',
                    'Bồn tắm',
                    'Vòi nước',
                    'Máy giặt',
                    'Chậu rửa',
                    'Xô nước',
                    'Bình nước nóng',
                    'Bình lọc nước',
                    'Giá phơi đồ',
                    'Bàn ủi hơi nước',
                    'Nồi áp suất (hơi)',
                    'Máy làm đá',
                    'Tủ lạnh',
                    'Máy hút ẩm'],
    'khoang_san': [   'Ngọc trai đen',
                      'Aquamarine',
                      'Lapis lazuli',
                      'Labradorite',
                      'Obsidian đen',
                      'Onyx đen',
                      'Hematite',
                      'Moonstone',
                      'Sapphire xanh đậm',
                      'Tanzanite'],
    'ky_thuat_so': [   'Cloud computing',
                       'Streaming',
                       'Flow/pipeline data',
                       'VPN (tunnel)',
                       'Crypto liquidity',
                       'Dark web',
                       'Deep web',
                       'Torrent',
                       'Spotify/Apple Music'],
    'my_pham': [   'Nước hoa',
                   'Perfume',
                   'Kem dưỡng ẩm',
                   'Serum hyaluronic',
                   'Toner',
                   'Micellar water',
                   'Sữa rửa mặt',
                   'Kem chống nắng dạng gel',
                   'Mặt nạ sheet',
                   'Xịt khoáng',
                   'Dầu dưỡng tóc'],
    'nghe_thuat': [   'Tranh phong cảnh biển',
                      'Tranh thủy mặc (nước)',
                      'Nghệ thuật đá lỏng (resin art)',
                      'Thủy tinh nghệ thuật',
                      'Điêu khắc băng (ice sculpture)',
                      'Múa đương đại (flowing)'],
    'nhac_cu': [   'Trống nước',
                   'Đàn bầu',
                   'Kèn ốc biển',
                   'Steel drum (Trinidad)',
                   'Rain stick',
                   'Ocean drum',
                   'Sáo nước',
                   'Waterphone'],
    'noi_that': [   'Bể cá',
                    'Đài phun nước mini',
                    'Gương soi',
                    'Rèm xanh navy',
                    'Thảm xanh đậm',
                    'Đèn nước (lava lamp)',
                    'Bình thủy sinh',
                    'Tranh biển',
                    'Đồng hồ cát',
                    'Bình hoa thủy tinh'],
    'nong_nghiep': [   'Hệ thống tưới nhỏ giọt',
                       'Ao nuôi cá',
                       'Bè nuôi tôm',
                       'Ruộng muối',
                       'Trại nuôi tôm hùm',
                       'Đầm nuôi ngao',
                       'Hồ nuôi cá tra',
                       'Bè cá lồng'],
    'phuong_tien': {   'Lâm Quan': ['Thuyền máy', 'Ca nô', 'Tàu cá lớn', 'Phà chở xe'],
                       'Suy': ['Thuyền cũ', 'Xuồng hỏng', 'Bè mục'],
                       'chung': ['Thuyền', 'Tàu thủy', 'Canoe', 'Kayak', 'Phà', 'Xuồng', 'Bè'],
                       'Đế Vượng': ['Du thuyền siêu sang', 'Tàu sân bay', 'Tàu ngầm hạt nhân', 'Cruise ship']},
    'quoc_gia': [   'Phương Bắc',
                    'Bắc Cực',
                    'Scandinavia',
                    'Canada',
                    'Russia',
                    'New Zealand',
                    'Iceland',
                    'Nhật Bản (biển)',
                    'Maldives (đảo)'],
    'the_thao': [   'Bơi',
                    'Lặn',
                    'Lướt ván',
                    'Kayak',
                    'Cano',
                    'Đua thuyền',
                    'Polo nước',
                    'Nhảy cầu',
                    'Trượt nước',
                    'Lướt sóng',
                    'Bóng nước',
                    'Câu cá thể thao'],
    'thoi_tiet': [   'Mưa to',
                     'Bão biển',
                     'Sóng thần',
                     'Lũ lụt',
                     'Mưa phùn',
                     'Sương mù',
                     'Tuyết rơi',
                     'Mưa đá',
                     'Gió mùa Đông Bắc'],
    'thuc_pham_chi_tiet': {   'chung': [   'Cá thu',
                                           'Cá hồi',
                                           'Cá ngừ',
                                           'Tôm hùm',
                                           'Cua hoàng đế',
                                           'Sò huyết',
                                           'Ốc hương',
                                           'Bào ngư',
                                           'Hàu',
                                           'Mực',
                                           'Bạch tuộc',
                                           'Sứa',
                                           'Rong biển',
                                           'Tảo spirulina',
                                           'Muối biển',
                                           'Nước mắm Phú Quốc',
                                           'Cá khô',
                                           'Tôm khô',
                                           'Mắm ruốc',
                                           'Mắm tôm',
                                           'Mắm cá',
                                           'Dưa hấu',
                                           'Dưa gang',
                                           'Thạch dừa',
                                           'Chè đậu đen',
                                           'Súp (phở, bún, mì nước)',
                                           'Canh',
                                           'Cháo',
                                           'Lẩu'],
                              'do_uong': [   'Nước suối',
                                             'Nước khoáng',
                                             'Nước dừa',
                                             'Trà đá',
                                             'Cà phê sữa đá',
                                             'Bia',
                                             'Rượu vang',
                                             'Rum',
                                             'Gin',
                                             'Whisky',
                                             'Champagne',
                                             'Cocktail',
                                             'Smoothie',
                                             'Sinh tố',
                                             'Sữa tươi',
                                             'Sữa chua',
                                             'Trà sữa',
                                             'Nước ép',
                                             'Coconut water',
                                             'Matcha latte']},
    'ton_giao': [   'Nước thánh',
                    'Rửa tội',
                    'Bình tịnh thủy (Quan Âm)',
                    'Hồ sen chùa',
                    'Sông Hằng (Ấn Độ)',
                    'Phép rửa',
                    'Nước cúng',
                    'Cốc nước thờ'],
    'trang_phuc': {   'Suy': ['Áo mưa rách', 'Ủng cũ', 'Áo tắm cũ'],
                      'chung': [   'Áo tắm',
                                   'Đồ lặn (wetsuit)',
                                   'Áo phao',
                                   'Ống chân nhái',
                                   'Kính lặn',
                                   'Áo mưa',
                                   'Ủng cao su',
                                   'Áo khoác chống nước',
                                   'Mũ thủy thủ'],
                      'Đế Vượng': ['Bộ đồ lặn chuyên nghiệp', 'Bikini nhung', 'Áo mưa Burberry']},
    'van_phong': [   'Mực in',
                     'Bút bi (mực lỏng)',
                     'Bút máy',
                     'Sơn marker',
                     'Bảng trắng (xóa ướt)',
                     'Máy hủy giấy (dầu bôi trơn)',
                     'Bình xịt khử mùi văn phòng'],
    'y_te': [   'Thuốc nước/siro',
                'Dịch truyền',
                'Nước muối sinh lý',
                'Thuốc nhỏ mắt',
                'Thuốc nhỏ mũi',
                'Oxy già',
                'Cồn sát trùng',
                'Gel khử khuẩn',
                'Nước súc miệng',
                'Thuốc tẩy giun (lỏng)',
                'Kem bôi da',
                'Mỡ tra mắt',
                'Huyết tương',
                'Máu truyền',
                'Nước ối',
                'Thụt rửa']}
