"""12 Trường Sinh - Trạng thái vật chất (dùng chung cho 5 hành)"""

TRUONG_SINH_TRANG_THAI = {   'Bệnh': {   'am_thanh': 'Tiếng kêu lạch cạch, rè, khò khè, không đều',
                'cap': '🟠 Bệnh',
                'chat_luong': 'KÉM, không đáng tin, hay trục trặc',
                'huong_phat_trien': 'Đang xuống dốc, cần can thiệp',
                'kich_thuoc': 'Nhỏ lại, méo mó, biến dạng nhẹ',
                'nhiet_do': 'Lạnh, ẩm ướt, có mùi ẩm mốc',
                'so': [4],
                'so_luong': '1-3',
                'tinh_trang': 'HỎNG VẶT, có vấn đề, chạy chập chờn, lỗi',
                'trong_luong': 'Nhẹ, lỏng lẻo, mong manh',
                'tuoi_vat': 'Cũ, cần sửa chữa, nhiều vết xước/lõm'},
    'Dưỡng': {   'am_thanh': 'Tiếng nhẹ nhàng, êm ái, ru',
                 'cap': '💜🟢 Nuôi dưỡng',
                 'chat_luong': 'ĐANG CẢI THIỆN từng ngày, triển vọng tốt',
                 'huong_phat_trien': 'Đang lớn dần, sắp ra ánh sáng',
                 'kich_thuoc': 'Nhỏ nhưng đang lớn dần',
                 'nhiet_do': 'Ấm áp (được giữ ấm, ấp)',
                 'so': [2, 6],
                 'so_luong': '1-2',
                 'tinh_trang': 'ĐANG ĐƯỢC CHĂM SÓC, nuôi dưỡng, ấp ủ',
                 'trong_luong': 'Nhẹ nhưng đang nặng dần',
                 'tuoi_vat': 'Từ mầm non, đang phát triển, được bảo vệ'},
    'Lâm Quan': {   'am_thanh': 'Tiếng mạnh, rõ ràng, vang dội',
                    'cap': '🟢🟢 Vượng',
                    'chat_luong': 'RẤT TỐT, bền bỉ, đáng tin cậy',
                    'huong_phat_trien': 'Đang đỉnh cao, phát triển mạnh',
                    'kich_thuoc': 'Lớn, to khỏe, đầy đặn',
                    'nhiet_do': 'Ấm nóng (đang hoạt động)',
                    'so': [5, 7],
                    'so_luong': '3-5',
                    'tinh_trang': 'ĐANG DÙNG, hoạt động tốt, hiệu suất cao',
                    'trong_luong': 'Nặng, chắc chắn, có trọng lượng',
                    'tuoi_vat': 'Đang ở prime, sử dụng hàng ngày, rất hữu ích'},
    'Mộ': {   'am_thanh': 'Im lìm, bị bịt, không có tiếng, nghẹn',
              'cap': '🔴 Chôn/Cất',
              'chat_luong': 'CŨ nhưng CÓ GIÁ TRỊ tiềm ẩn (đồ cổ, kỷ niệm)',
              'huong_phat_trien': 'Bị giữ lại, chờ ai đó tìm thấy',
              'kich_thuoc': 'Nhỏ gọn, bị nén, bị ép',
              'nhiet_do': 'Lạnh, tối, ẩm (dưới đất, trong kho)',
              'so': [4, 8],
              'so_luong': '1 (duy nhất, cô lập)',
              'tinh_trang': 'BỊ CẤT KỸ, chôn giấu, khóa lại, niêm phong',
              'trong_luong': 'Nặng (bị chất đống) hoặc nhẹ (bị quên trong hộp)',
              'tuoi_vat': 'Cũ, lâu năm, cổ vật, đồ xưa, bị quên lãng'},
    'Mộc Dục': {   'am_thanh': 'Tiếng nước chảy, tiếng lau chùi, tiếng rửa',
                   'cap': '🟡 Tắm gội',
                   'chat_luong': 'KHÔNG ỔN ĐỊNH, lúc tốt lúc xấu, dễ hỏng vặt',
                   'huong_phat_trien': 'Đang được cải thiện, chưa hoàn chỉnh',
                   'kich_thuoc': 'Nhỏ → vừa, đang phát triển',
                   'nhiet_do': 'Ấm (vừa tiếp xúc nước/dung dịch)',
                   'so': [2],
                   'so_luong': '1-3',
                   'tinh_trang': 'Đang được CHỈNH SỬA, tân trang, có vết trầy xước nhẹ',
                   'trong_luong': 'Nhẹ - trung bình',
                   'tuoi_vat': 'Mới dùng 1-2 lần, hơi cũ nhưng còn tốt'},
    'Quan Đới': {   'am_thanh': 'Tiếng mặc đồ, tiếng đeo, tiếng chuẩn bị',
                    'cap': '🟢 Trưởng thành',
                    'chat_luong': 'Tốt, đang trong giai đoạn tốt nhất',
                    'huong_phat_trien': 'Sắp đạt đỉnh, chuẩn bị tỏa sáng',
                    'kich_thuoc': 'Vừa phải, cân đối',
                    'nhiet_do': 'Mát mẻ, dễ chịu',
                    'so': [3],
                    'so_luong': '2-3',
                    'tinh_trang': 'CHUẨN BỊ DÙNG, mới mặc/đeo, sẵn sàng',
                    'trong_luong': 'Trung bình, vừa tay',
                    'tuoi_vat': 'Mới mua, đang học cách sử dụng'},
    'Suy': {   'am_thanh': 'Tiếng nhỏ dần, hơi rè, không còn trong trẻo',
               'cap': '🟡 Bắt đầu suy',
               'chat_luong': 'VẪN DÙNG ĐƯỢC nhưng kém hơn trước, có lỗi nhỏ',
               'huong_phat_trien': 'Đang đi xuống, cần chăm sóc',
               'kich_thuoc': 'Vừa → nhỏ dần, hơi co lại',
               'nhiet_do': 'Hơi lạnh, bắt đầu nguội',
               'so': [4, 6],
               'so_luong': '2-4',
               'tinh_trang': 'BẮT ĐẦU CŨ, có vết bẩn, trầy xước, phai màu',
               'trong_luong': 'Nhẹ dần, bớt chắc chắn',
               'tuoi_vat': 'Đã dùng lâu, bắt đầu lỗi thời, hết trend'},
    'Thai': {   'am_thanh': 'Tiếng rất nhỏ, thì thầm, ý nghĩ',
                'cap': '💜 Thai nghén',
                'chat_luong': 'TIỀM NĂNG, chưa biết tốt xấu, chờ đợi',
                'huong_phat_trien': 'Sắp sinh ra, đầy hứa hẹn',
                'kich_thuoc': 'Cực nhỏ, vi mô, mầm mống',
                'nhiet_do': 'Ấm bên trong (được ấp ủ)',
                'so': [1, 6],
                'so_luong': '0-1 (sắp có)',
                'tinh_trang': 'ĐANG HÌNH THÀNH, chưa rõ hình dạng, mơ hồ',
                'trong_luong': 'Gần như không trọng lượng',
                'tuoi_vat': 'Chưa sinh ra, đang thai nghén, ý tưởng, bản vẽ'},
    'Trường Sinh': {   'am_thanh': 'Tiếng nhỏ, yếu ớt, mới phát ra',
                       'cap': '🟢 Mới sinh',
                       'chat_luong': 'Tốt nhưng chưa ổn định, cần phát triển thêm',
                       'huong_phat_trien': 'Đang lớn lên, sẽ mạnh dần',
                       'kich_thuoc': 'Nhỏ, mới hình thành',
                       'nhiet_do': 'Ấm nhẹ (khí mới sinh)',
                       'so': [1],
                       'so_luong': '1-2',
                       'tinh_trang': 'MỚI TINH, vừa xuất hiện, chưa dùng',
                       'trong_luong': 'Nhẹ, gọn',
                       'tuoi_vat': 'Mới ra lò, vừa sản xuất, còn nguyên seal'},
    'Tuyệt': {   'am_thanh': 'TUYỆT ĐỐI IM LẶNG, hư vô',
                 'cap': '🔴🔴 Tuyệt diệt',
                 'chat_luong': 'KHÔNG CÒN GIÁ TRỊ, rác, bụi, tro',
                 'huong_phat_trien': 'Đã kết thúc hoàn toàn, chờ chu kỳ mới',
                 'kich_thuoc': 'CỰC NHỎ hoặc đã tan biến, gần như không còn',
                 'nhiet_do': 'Không cảm nhận được (đã tan biến)',
                 'so': [0],
                 'so_luong': '0',
                 'tinh_trang': 'TAN RÃ, vỡ vụn, phân hủy, biến mất, bốc hơi',
                 'trong_luong': 'Gần bằng 0, bay theo gió',
                 'tuoi_vat': 'Đã bị phá hủy, không thể phục hồi, bụi tro'},
    'Tử': {   'am_thanh': 'IM LẶNG, không phát ra âm thanh, câm',
              'cap': '🔴 Chết',
              'chat_luong': 'PHẾ PHẨM, không giá trị, bỏ đi',
              'huong_phat_trien': 'Đã hết, không cứu được',
              'kich_thuoc': 'RẤT NHỎ, teo lại, co quắp',
              'nhiet_do': 'LẠNH NGẮT, không có nhiệt, tê liệt',
              'so': [0],
              'so_luong': '0-1',
              'tinh_trang': 'HỎNG HẲN, không hoạt động, chết máy, đứng hình',
              'trong_luong': 'Rất nhẹ (đã mất phần bên trong) hoặc nặng trĩu (chết cứng)',
              'tuoi_vat': 'Rất cũ, bỏ không dùng, vứt xó, phế liệu'},
    'Đế Vượng': {   'am_thanh': 'Tiếng lớn, hùng hồn, vang xa, uy nghiêm',
                    'cap': '🟢🟢🟢 Cực vượng',
                    'chat_luong': 'HOÀN HẢO, cao cấp nhất, sang trọng, xa xỉ',
                    'huong_phat_trien': 'Đỉnh điểm rồi, sẽ bắt đầu đi xuống',
                    'kich_thuoc': 'CỰC LỚN, hoành tráng, nổi bật',
                    'nhiet_do': 'NÓNG, nhiệt lượng cao, bừng bừng',
                    'so': [9, 10],
                    'so_luong': '5-9',
                    'tinh_trang': 'ĐỈNH CAO, hoàn hảo, toàn vẹn, lung linh',
                    'trong_luong': 'Rất nặng, đồ sộ, uy nghi',
                    'tuoi_vat': 'Đang ở đỉnh cao nhất, được mọi người biết đến'}}
