"""Vạn Vật — Hành Hỏa (CORE + EXPANDED)"""

# CORE: 5 giác quan, đồ vật theo 12 tầng, con người, bệnh, thú, cây
CORE = {   'benh_tat': {   'chung': 'Bệnh TIM, MẠCH MÁU, MẮT (viêm), RUỘT NON, lưỡi',
                    'cu_the': [   'Nhồi máu cơ tim',
                                  'Đột quỵ',
                                  'Cao huyết áp',
                                  'Viêm mắt',
                                  'Sốt cao',
                                  'Viêm ruột',
                                  'Lở loét miệng',
                                  'Nóng trong',
                                  'Mụn nhọt',
                                  'Bỏng',
                                  'Nhiễm trùng',
                                  'Viêm da mẩn đỏ',
                                  'Mất ngủ do nóng'],
                    'vi_tri': 'Tim, ruột non, mắt, lưỡi, mạch máu, não'},
    'chat_lieu': 'Đèn, nến, nhựa (cháy), sợi tổng hợp, điện tử, pin, acquy',
    'con_nguoi': {   'Bệnh': 'Người bệnh tim, huyết áp cao, mặt đỏ, hay bừng nóng, khó thở',
                     'Dưỡng': 'Em bé hiếu động, thực tập sinh marketing, idol trainee',
                     'Lâm Quan': 'MC truyền hình, đầu bếp nổi tiếng, marketer giỏi — tự tin, sáng rỡ',
                     'Mộ': 'Nghệ sĩ ẩn dật, người sống trong ký ức quá khứ huy hoàng',
                     'Suy': 'Nghệ sĩ hết thời, diễn viên quá đát — mệt mỏi, buồn, hơi mập',
                     'Thai': 'Thai nhi, ý tưởng nghệ thuật, startup sắp ra mắt',
                     'Tuyệt': 'Người bị quên lãng, ngôi sao lụi tàn, không ai nhớ',
                     'Tử': 'Người đột quỵ, nhồi máu, sốc nhiệt — mặt tím tái',
                     'giong_noi': 'To, nhanh, sôi nổi, nhiệt tình, hay cười',
                     'nghe_nghiep': 'Nghệ sĩ, MC, diễn viên, đầu bếp, thợ hàn, lính cứu hỏa, nhà báo, marketer, KOL',
                     'ngoai_hinh': 'Da đỏ/hồng, mặt nhọn/tam giác, mắt sáng, tóc xoăn/đỏ nâu',
                     'than_hinh': 'Trung bình, nhanh nhẹn, linh hoạt, hay vung tay',
                     'tinh_cach': 'Nóng tính, nhiệt huyết, tràn đầy năng lượng, sáng tạo, bốc đồng',
                     'Đế Vượng': 'Ngôi sao nổi tiếng, CEO công nghệ, KOL triệu followers — sáng bóng, nổi bật, ăn mặc '
                                 'lộng lẫy'},
    'do_vat': {   'Bệnh': [   'Đèn nhấp nháy',
                              'Bóng đèn sắp cháy',
                              'Pin phồng',
                              'Tivi nhiễu',
                              'Bếp gas rò rỉ',
                              'Ổ điện cháy'],
                  'Dưỡng': ['Đốm lửa nhỏ', 'Than hồng', 'Bếp đang nhóm', 'Đèn dimmer', 'Nến mới thắp'],
                  'Lâm Quan': [   'Bếp gas',
                                  'Lò vi sóng',
                                  'Tivi',
                                  'Máy tính chơi game',
                                  'Đèn LED',
                                  'Bóng đèn',
                                  'Bật lửa Zippo'],
                  'Mộ': ['Than đá trong mỏ', 'Dầu mỏ dưới đất', 'Núi lửa ngủ', 'Lò nung cổ', 'Đuốc trong hầm mộ'],
                  'Mộc Dục': ['Đèn vừa lau', 'Lò vừa vệ sinh', 'Que diêm vừa sấy', 'Bóng đèn lau sạch'],
                  'Quan Đới': ['Nến thơm mới', 'Pin mới', 'Bóng đèn mới', 'Match que diêm', 'Đèn bàn'],
                  'Suy': ['Đèn mờ', 'Nến cháy gần hết', 'Pin yếu', 'Tivi cũ', 'Bếp gas lửa yếu', 'Bật lửa sắp hết gas'],
                  'Thai': ['Magma dưới đất', 'Tia lửa sắp bùng', 'Ý tưởng phim', 'Kịch bản chưa quay'],
                  'Trường Sinh': ['Tia lửa nhỏ', 'Đốm sáng', 'LED nhỏ', 'Pin cúc áo', 'Ngọn nến nhỏ'],
                  'Tuyệt': ['Tro tàn', 'Khói tan', 'Tia lửa tắt', 'Bụi than', 'Màn đêm tối đen'],
                  'Tử': ['Đèn tắt', 'Nến tàn', 'Pin chết', 'Bóng đèn cháy', 'Tivi vỡ', 'Than tro nguội', 'Diêm hết'],
                  'Đế Vượng': [   'Lò sưởi lớn',
                                  'Hệ thống chiếu sáng sân vận động',
                                  'Tivi 85 inch',
                                  'Pháo hoa hoành tráng',
                                  'Đuốc Olympic',
                                  'Lò phản ứng hạt nhân',
                                  'Đèn pha sân khấu']},
    'dong_vat': {   'Suy': 'Ve sầu cuối hạ, đom đóm leo lắt — sắp tắt',
                    'chung': 'Chim phượng, công, ngựa, cừu, ve sầu, đom đóm, bọ cánh cứng đỏ',
                    'Đế Vượng': 'Phượng hoàng (biểu tượng), công đực xòe đuôi — rực rỡ'},
    'gio': 'Tỵ-Ngọ (9h-13h)',
    'hanh': 'Hỏa',
    'hinh_dang': 'Nhọn, tam giác, hình ngọn lửa, hình nón, tháp',
    'huong': 'Nam',
    'khuu_giac': {   'mui': 'Mùi khói, mùi cháy, mùi nóng, mùi nhựa nóng',
                     'mui_dac_trung': 'Mùi than nướng, mùi hương trầm cháy, mùi pháo nổ, mùi nến thơm'},
    'mau_sac': 'Đỏ, cam, tím, hồng, đỏ rực, đỏ tươi, đỏ son',
    'mua': 'Hạ',
    'ngay': 'Thứ 3 (Hỏa nhật)',
    'nha_cua': {   'Mộ': 'Nhà dưới hầm, phòng tối, studio ngầm',
                   'Suy': 'Nhà thiếu ánh sáng, bếp gas cũ, đèn mờ',
                   'chung': 'Nhà nhiều cửa kính, nhà hướng Nam, nhiều ánh sáng, bếp lửa',
                   'Đế Vượng': 'Penthouse view thành phố rực sáng, nhà hàng, sân khấu, studio'},
    'thi_giac': {   'anh_sang': 'Tỏa sáng, lấp lánh, rực rỡ, chói loa',
                    'be_mat': 'Bóng (khi cháy), gập ghềnh (tro, than)',
                    'do_trong': 'Sáng rực, phát quang',
                    'mau': 'Đỏ rực, cam cháy, tím ánh, hồng sen'},
    'thinh_giac': {   'am_thanh': 'Tiếng lửa cháy tí tách, tiếng nổ, tiếng bùng',
                      'giong_noi': 'To, nhanh, nhiệt huyết, nồng nhiệt, sôi nổi',
                      'nhac_cu': 'Trống, thanh la, kèn trumpet, guitar điện'},
    'thuc_vat': {   'Suy': 'Hoa héo, cánh rụng, lá vàng mùa thu — tàn phai',
                    'chung': 'Hoa hồng đỏ, hoa phượng, hoa gạo, ớt, hoa tulip đỏ',
                    'Đế Vượng': 'Hoa phượng nở rực trời, mùa hoa ban đỏ — lộng lẫy'},
    'tinh_chat': 'Nóng, sáng, bùng cháy, lan tỏa, mạnh mẽ, biến đổi nhanh',
    'vi_giac': {   'thuc_pham': 'BBQ, đồ nướng, cà phê, sô cô la đen, rau đắng, thuốc nam',
                   'vi': 'Đắng (khổ qua, cà phê đen, trà đặc, thuốc)'},
    'xuc_giac': {   'be_mat': 'Khô, nóng, có thể bỏng',
                    'cam_giac': 'Nóng, bỏng, châm chích, khô ráo',
                    'nhiet_do': 'NÓNG, từ ấm đến bỏng tay',
                    'trong_luong': 'Nhẹ (lửa, ánh sáng không có trọng lượng)'}}

# EXPANDED: Phương tiện, Trang phục, Thực phẩm, Khoáng sản, Công nghệ...
EXPANDED = {   'bo_phan_co_the': [   'Tim',
                          'Ruột non',
                          'Mắt (viêm)',
                          'Lưỡi',
                          'Mạch máu',
                          'Não',
                          'Hệ thần kinh',
                          'Tuyến thượng thận',
                          'Da (viêm đỏ)'],
    'cam_xuc': [   'Vui vẻ',
                   'Hạnh phúc',
                   'Nhiệt huyết',
                   'Đam mê',
                   'Giận dữ',
                   'Phấn khích',
                   'Tự hào',
                   'Nóng nảy',
                   'Bốc đồng',
                   'Yêu thương mãnh liệt'],
    'cong_nghe': {   'Suy': ['TV CRT cũ', 'Đèn huỳnh quang nhấp nháy'],
                     'chung': [   'Tivi OLED',
                                  'Màn hình LED',
                                  'Đèn LED',
                                  'Laser',
                                  'Máy chiếu',
                                  'Camera hồng ngoại',
                                  'Kính AR/VR',
                                  'Drone camera',
                                  'Màn hình quảng cáo điện tử',
                                  'Billboard LED'],
                     'Đế Vượng': ['Hệ thống laser show', 'Màn hình Times Square', 'Hologram']},
    'cong_nghiep': [   'Lò nung',
                       'Lò phản ứng',
                       'Nhà máy điện',
                       'Nhà máy nhiệt',
                       'Xưởng hàn',
                       'Lò đúc',
                       'Nhà máy thủy tinh',
                       'Xưởng gốm nung'],
    'dia_ly': [   'Sa mạc Sahara',
                  'Thung lũng Chết',
                  'Miệng núi lửa',
                  'Suối nước nóng',
                  'Vùng xích đạo',
                  'Dubai',
                  'Death Valley',
                  'Đảo Hawaii (núi lửa)'],
    'do_tre_em': [   'Đèn ngủ hình sao',
                     'Pháo bông',
                     'Đèn lồng',
                     'Kính vạn hoa',
                     'Búp bê barbie',
                     'Xe đồ chơi điều khiển',
                     'Slime phát sáng'],
    'gia_dung': [   'Bếp gas',
                    'Bếp điện',
                    'Bếp từ',
                    'Lò nướng',
                    'Lò vi sóng',
                    'Nồi chiên không dầu',
                    'Máy nướng bánh mì',
                    'Ấm đun siêu tốc',
                    'Lò sưởi',
                    'Quạt sưởi',
                    'Bàn ủi',
                    'Máy sấy tóc',
                    'Máy uốn tóc',
                    'Bếp nướng BBQ'],
    'khoang_san': [   'Ruby',
                      'Garnet',
                      'Fire opal',
                      'Sunstone',
                      'Carnelian',
                      'Jasper đỏ',
                      'Rhodolite',
                      'Spinel đỏ',
                      'Amber (hổ phách đỏ)'],
    'ky_thuat_so': [   'Social media (viral)',
                       'YouTube',
                       'TikTok',
                       'Instagram',
                       'Livestream',
                       'Gaming esports',
                       'Trending',
                       'Viral marketing',
                       'Influencer',
                       'Meme'],
    'my_pham': [   'Son môi đỏ',
                   'Mascara',
                   'Eyeliner',
                   'Phấn highlight',
                   'Bronzer',
                   'Blush đỏ',
                   'Nail polish đỏ',
                   'Body glitter'],
    'nghe_thuat': [   'Sơn dầu',
                      'Tranh acrylic',
                      'Múa lửa',
                      'Graffiti (spray paint)',
                      'Neon art',
                      'Light painting (nhiếp ảnh)',
                      'Fire dance',
                      'Fireworks art'],
    'nhac_cu': [   'Trống lớn',
                   'Trống snare',
                   'Tom-tom',
                   'Bongo',
                   'Conga',
                   'Guitar điện',
                   'Bass điện',
                   'Synthesizer',
                   'DJ Turntable',
                   'Kèn trumpet',
                   'Kèn tuba',
                   'Trống điện tử',
                   'Sampler'],
    'noi_that': [   'Đèn chùm',
                    'Đèn bàn',
                    'Đèn ngủ',
                    'Nến thơm',
                    'Lò sưởi trang trí',
                    'Rèm đỏ',
                    'Thảm đỏ',
                    'Gương có đèn LED',
                    'Đèn strip LED',
                    'Quạt trần (có đèn)',
                    'Kệ đèn',
                    'Tranh đèn neon'],
    'nong_nghiep': [   'Đốt đồng',
                       'Phát rẫy đốt nương',
                       'Lò sấy nông sản',
                       'Máy sấy thóc',
                       'Lò hun khói',
                       'Lò nướng bánh',
                       'Hệ thống sưởi nhà kính'],
    'phuong_tien': {   'Lâm Quan': ['Xe Vespa đỏ', 'Xe bus 2 tầng London', 'Xe cứu thương'],
                       'Suy': ['Xe pháo cũ', 'Xe cứu hỏa nghỉ hưu'],
                       'chung': ['Xe đua F1', 'Xe mô tô sport', 'Xe điện Tesla', 'Xe chữa cháy'],
                       'Đế Vượng': ['Tên lửa SpaceX', 'Xe đua Nascar', 'Siêu xe Ferrari đỏ']},
    'quoc_gia': [   'Phương Nam',
                    'Úc (nắng)',
                    'Ấn Độ',
                    'Dubai',
                    'Bắc Phi (Sahara)',
                    'Mexico',
                    'Spain',
                    'Italy (thời trang, ẩm thực)'],
    'the_thao': [   'Boxing',
                    'MMA',
                    'Kickboxing',
                    'Chạy marathon',
                    'Chạy nước rút',
                    'Đua xe F1',
                    'Đua moto',
                    'Bắn cung',
                    'Bắn súng thể thao',
                    'Thể dục dụng cụ',
                    'Nhảy hiện đại',
                    'Aerobic'],
    'thoi_tiet': [   'Nắng gắt',
                     'Hạn hán',
                     'Cháy rừng',
                     'Nóng bức',
                     'Sét đánh',
                     'Sóng nhiệt heat wave',
                     'Hiện tượng El Nino'],
    'thuc_pham_chi_tiet': {   'chung': [   'Thit nướng BBQ',
                                           'Steak bò',
                                           'Thịt xiên que',
                                           'Pizza lò nướng',
                                           'Bánh mì nướng',
                                           'Cơm cháy',
                                           'Popcorn',
                                           'Khoai tây chiên',
                                           'Gà rán KFC',
                                           'Tempura',
                                           'Chả giò',
                                           'Bánh tráng nướng',
                                           'Cà phê đen',
                                           'Sô cô la đen',
                                           'Khổ qua',
                                           'Trà đặc',
                                           'Thuốc đắng',
                                           'Ớt hiểm',
                                           'Tiêu Cayenne',
                                           'Habanero',
                                           'Tabasco'],
                              'do_uong': [   'Cà phê espresso',
                                             'Cà phê đen đá',
                                             'Trà đen Earl Grey',
                                             'Rượu brandy',
                                             'Cognac',
                                             'Tequila',
                                             'Mezcal',
                                             'Nước tăng lực Red Bull',
                                             'Monster Energy']},
    'ton_giao': [   'Hương',
                    'Nến thờ',
                    'Đèn dầu',
                    'Đuốc hỏa',
                    'Lửa thiêng',
                    'Pháo (đốt vàng mã)',
                    'Giấy tiền vàng bạc',
                    'Bếp thắp hương',
                    'Đèn hoa đăng',
                    'Đèn lồng Phật đản',
                    'Đèn cầy',
                    'Nhang trầm'],
    'trang_phuc': {   'Suy': ['Áo phai màu', 'Váy cũ', 'Trang phục hết mốt'],
                      'chung': [   'Áo đỏ',
                                   'Váy đỏ',
                                   'Giày đỏ',
                                   'Son môi đỏ',
                                   'Kính mắt thời trang',
                                   'Trang phục biểu diễn',
                                   'Đồ sequin lấp lánh',
                                   'Áo lông vũ',
                                   'Áo vest đỏ',
                                   'Cà vạt đỏ',
                                   'Mũ cowboy'],
                      'Đế Vượng': ['Váy dạ hội Oscar', 'Áo choàng vua/hoàng hậu đỏ', 'Bộ sưu tập Valentino đỏ']},
    'van_phong': [   'Máy hủy tài liệu (nhiệt)',
                     'Máy ép plastic',
                     'Bảng LED thông báo',
                     'Đèn bàn',
                     'Máy photocopy (nhiệt)',
                     'Máy fax',
                     'Máy scan'],
    'y_te': [   'Laser phẫu thuật',
                'Đốt điện trị bệnh',
                'Xạ trị',
                'Hóa trị',
                'Tia UV khuẩn',
                'Đèn trị liệu ánh sáng',
                'Châm cứu (đốt moxa/ngải cứu)',
                'Sấy khô vết thương',
                'Thuốc viêm/sốt',
                'Paracetamol',
                'Ibuprofen',
                'Vitamin C (chống oxy hóa)',
                'Kem chống bỏng',
                'Gel hạ sốt']}
