"""Vạn Vật — Hành Thổ (CORE + EXPANDED)"""

# CORE: 5 giác quan, đồ vật theo 12 tầng, con người, bệnh, thú, cây
CORE = {   'benh_tat': {   'chung': 'Bệnh DẠ DÀY, LÁCH, MIỆNG, cơ bắp, da thịt',
                    'cu_the': [   'Đau dạ dày',
                                  'Viêm loét dạ dày',
                                  'Béo phì',
                                  'Tiểu đường type 2',
                                  'Viêm lách',
                                  'Đầy bụng',
                                  'Khó tiêu',
                                  'Nấm da',
                                  'Mụn cóc',
                                  'Sưng phù',
                                  'Ung thư dạ dày',
                                  'Viêm miệng lưỡi',
                                  'Teo cơ',
                                  'Loãng xương'],
                    'vi_tri': 'Dạ dày, lách, miệng, cơ bắp, mô mỡ, da thịt'},
    'chat_lieu': 'Đất, đá, gạch, xi măng, bê tông, gốm sứ, thủy tinh đục, sành',
    'con_nguoi': {   'Bệnh': 'Người bệnh dạ dày, đầy bụng, khó tiêu, sưng phù — bụng to, mặt vàng',
                     'Dưỡng': 'Em bé mập, trẻ nhỏ khoẻ, thợ xây học việc, nông dân mới bắt đầu',
                     'Lâm Quan': 'Kiến trúc sư, kỹ sư xây dựng, nông dân giàu — chắc khỏe, đáng tin',
                     'Mộ': 'Người giữ kho, bảo tàng, thợ đào mộ, khảo cổ — bí ẩn, trầm lặng',
                     'Suy': 'Nông dân nghèo, thợ xây mệt, kế toán stress — mệt, vai gù',
                     'Thai': 'Thai nhi, ý tưởng kinh doanh bđs, sinh viên kiến trúc',
                     'Tuyệt': 'Người bị mất đất, vô gia cư sống ngoài đường, lang thang',
                     'Tử': 'Người dinh dưỡng kém, gầy gò xanh xao, không ăn được — thiếu sức sống',
                     'giong_noi': 'Trầm, chậm, nặng, đều đều, ít nói, nói gì chắc nấy',
                     'nghe_nghiep': 'Nhà nông, xây dựng, kiến trúc, bất động sản, đầu bếp, thợ gốm, kế toán',
                     'ngoai_hinh': 'Da vàng/nâu, mặt vuông, má bầu, mũi to, môi dày, tóc dày đen',
                     'than_hinh': 'MẬP, thấp, chắc khỏe, bụng to, vai rộng, tay chân chắc',
                     'tinh_cach': 'Trung thực, kiên nhẫn, chung thủy, bảo thủ, chậm rãi, đáng tin',
                     'Đế Vượng': 'Đại gia bất động sản, địa chủ lớn, chủ công ty xây dựng — mập, da vàng, đeo vàng '
                                 'nặng trĩu, uy nghi'},
    'do_vat': {   'Bệnh': ['Tường nứt', 'Nền lún', 'Gạch vỡ vụn', 'Sàn trơn trượt', 'Đất ô nhiễm'],
                  'Dưỡng': ['Đất đang ủ phân', 'Gốm đang nung', 'Xi măng đang đổ', 'Tường đang xây', 'Nền đang san'],
                  'Lâm Quan': ['Bàn gạch', 'Tượng gốm', 'Chậu sứ', 'Gạch lát', 'Bê tông', 'Tường nhà', 'Bao xi măng'],
                  'Mộ': ['Mộ phần', 'Đất chôn kho báu', 'Hầm đất', 'Hang động', 'Đá quý trong mỏ', 'Gốm cổ chôn'],
                  'Mộc Dục': ['Bát đĩa rửa sạch', 'Sàn nhà lau xong', 'Gạch mới rửa', 'Tường sơn lại'],
                  'Quan Đới': ['Bát đĩa sứ mới', 'Chậu cây mới', 'Gạch xây mới', 'Đất trồng', 'Bình gốm'],
                  'Suy': ['Tường loang lổ', 'Gạch vỡ', 'Bát mẻ', 'Sàn nứt', 'Đất khô cằn', 'Tượng bạc màu'],
                  'Thai': ['Đất sét nhồi (chưa nặn)', 'Bản vẽ kiến trúc', 'Đá thô chưa đẽo', 'Ý tưởng xây nhà'],
                  'Trường Sinh': ['Hòn sỏi nhỏ', 'Viên đất sét', 'Hạt cát', 'Viên gạch nhỏ', 'Nắp chén'],
                  'Tuyệt': ['Bụi đất', 'Cát bay sa mạc', 'Đá vôite tan', 'Sỏi nghiền', 'Tro than'],
                  'Tử': [   'Gạch vỡ nát',
                            'Tường đổ',
                            'Bình vỡ',
                            'Đất chết (không trồng được)',
                            'Cát bỏ hoang',
                            'Tro tàn đất'],
                  'Đế Vượng': [   'Tòa nhà cao tầng',
                                  'Kim tự tháp',
                                  'Bức tường thành',
                                  'Đất ruộng mênh mông',
                                  'Tượng Phật lớn',
                                  'Container',
                                  'Xe tải lớn']},
    'dong_vat': {   'Mộ': 'Chuột chũi, dế, giun — sống trong hang dưới đất',
                    'Suy': 'Giun đất, kiến, sâu — nhỏ bé, sống dưới đất',
                    'chung': 'Trâu, bò, chó, dê, gấu, lợn, giun đất, kiến',
                    'Đế Vượng': 'Voi, tê giác, trâu rừng — lớn, nặng, uy nghi'},
    'gio': 'Sửu-Thìn-Mùi-Tuất (1h-3h, 7h-9h, 13h-15h, 19h-21h)',
    'hanh': 'Thổ',
    'hinh_dang': 'Vuông, khối, dày dặn, phẳng, bằng bệ',
    'huong': 'Trung Tâm (hoặc Tây Nam / Đông Bắc)',
    'khuu_giac': {   'mui': 'Mùi ĐẤT sau mưa, mùi đất ẩm, mùi gạch nung, mùi sét',
                     'mui_dac_trung': 'Mùi bùn, mùi ruộng đồng, mùi xi măng mới, mùi gốm nung'},
    'mau_sac': 'Vàng, nâu đất, cam đất, be, kem, terracotta',
    'mua': 'Cuối hạ / giao mùa',
    'ngay': 'Thứ 7 (Thổ nhật)',
    'nha_cua': {   'Mộ': 'Hầm ngầm, phòng kho, nhà mồ, hang động, nhà trong núi',
                   'Suy': 'Nhà cấp 4 cũ nát, tường loang, nền lún, mái dột',
                   'chung': 'Nhà gạch, nhà bê tông, chung cư, nhà trệt, nhà có sân rộng',
                   'Đế Vượng': 'Tòa nhà chọc trời, biệt thự lớn, đất đai mênh mông, lâu đài'},
    'thi_giac': {   'anh_sang': 'Ánh sáng ấm, mờ nhạt, tự nhiên, không chói',
                    'be_mat': 'Thô ráp, có hạt, có lỗ nhỏ (gốm), dày dặn',
                    'do_trong': 'Đục, không xuyên sáng, dày đặc',
                    'mau': 'Vàng đất, nâu sậm, be kem, cam đất, terracotta'},
    'thinh_giac': {   'am_thanh': 'Tiếng đất vỡ, tiếng gõ gốm, tiếng nghiền, tiếng nặng đặt xuống',
                      'giong_noi': 'Trầm, chậm, đều đặn, nặng nề, chắc chắn',
                      'nhac_cu': 'Cồng chiêng, trống đất, ocarina, xylophone'},
    'thuc_vat': {   'Suy': 'Khoai sắn héo, ngô khô, rau úa — sắp thu hoạch',
                    'chung': 'Khoai, sắn, ngô, lúa, nấm, địa y, cây mía',
                    'Đế Vượng': 'Cây đa cổ thụ, cây bồ đề — gốc to, bám đất chắc'},
    'tinh_chat': 'Nặng, chắc chắn, ổn định, dày, thấm hút',
    'vi_giac': {   'thuc_pham': 'Khoai lang, khoai tây, cơm, bánh mì, đường, mật ong, ngô, bí',
                   'vi': 'Ngọt (đường, mật ong, trái cây chín, khoai)'},
    'xuc_giac': {   'be_mat': 'Thô ráp, có hạt sần sùi, nặng tay',
                    'cam_giac': 'Nặng, thô, dày, chắc, ổn định',
                    'nhiet_do': 'Ấm nhẹ (giữ nhiệt tốt), mát khi dưới đất',
                    'trong_luong': 'NẶNG, rất nặng, cần sức để nhấc'}}

# EXPANDED: Phương tiện, Trang phục, Thực phẩm, Khoáng sản, Công nghệ...
EXPANDED = {   'bo_phan_co_the': [   'Dạ dày',
                          'Lách',
                          'Miệng',
                          'Cơ bắp',
                          'Mô mỡ',
                          'Da thịt',
                          'Môi',
                          'Nướu',
                          'Tuyến nước bọt',
                          'Tụy',
                          'Ruột non (phần dưới)'],
    'cam_xuc': [   'Trung thực',
                   'Kiên nhẫn',
                   'Bảo thủ',
                   'Lo lắng',
                   'Tin tưởng',
                   'Chung thủy',
                   'Trầm tĩnh',
                   'Cố chấp',
                   'Bình tĩnh',
                   'Vững vàng'],
    'cong_nghe': {   'chung': [   'Máy đào',
                                  'Máy trộn bê tông',
                                  'Cân điện tử',
                                  'Máy đo địa chất',
                                  'GPS đo đạc',
                                  'Drone khảo sát',
                                  'Máy quét 3D địa hình',
                                  'Sensor đo độ ẩm đất',
                                  'Trạm quan trắc']},
    'cong_nghiep': [   'Mỏ than',
                       'Mỏ đá',
                       'Nhà máy xi măng',
                       'Nhà máy gạch',
                       'Xưởng gốm sứ',
                       'Công trường xây dựng',
                       'Nhà máy thủy tinh',
                       'Xưởng đúc bê tông',
                       'Mỏ khoáng sản',
                       'Hầm mỏ'],
    'dia_ly': [   'Đồng bằng',
                  'Cao nguyên',
                  'Thung lũng',
                  'Hang động',
                  'Sa mạc',
                  'Đồi',
                  'Núi',
                  'Đảo',
                  'Bãi biển (cát)',
                  'Đồng ruộng',
                  'Rẫy',
                  'Trung tâm lục địa',
                  'Lòng chảo',
                  'Truông',
                  'Bãi bồi'],
    'do_tre_em': [   'Đất nặn Play-Doh',
                     'Cát động lực kinetic sand',
                     'Lego gạch',
                     'Đồ chơi xây dựng',
                     'Xe công trường đồ chơi',
                     'Búp bê gốm'],
    'gia_dung': [   'Bát sứ',
                    'Đĩa sứ',
                    'Chén trà',
                    'Ấm trà gốm',
                    'Bình hoa gốm',
                    'Chậu rửa đá',
                    'Thớt đá',
                    'Cối xay',
                    'Cối giã',
                    'Ống đũa gốm',
                    'Hũ muối chua',
                    'Chum sành',
                    'Vại sành',
                    'Nồi đất',
                    'Siêu thuốc đất'],
    'khoang_san': [   'Granite',
                      'Cẩm thạch (marble)',
                      'Đá vôi',
                      'Đá sa thạch',
                      'Slate',
                      'Tiger eye (mắt hổ)',
                      'Citrine',
                      'Topaz vàng',
                      'Jasper vàng',
                      'Đá thạch anh khói',
                      'Kim cương vàng',
                      'Đá mã não',
                      'Đất sét',
                      'Kaolin',
                      'Feldspar',
                      'Mica',
                      'Thạch cao'],
    'ky_thuat_so': [   'Database/storage',
                       'Data center',
                       'Hard drive',
                       'Backup & archive',
                       'App bất động sản',
                       'Google Maps/Earth',
                       'CAD (thiết kế xây dựng)',
                       'Metaverse real estate',
                       'Digital twin (xây dựng)'],
    'my_pham': [   'Kem nền',
                   'Foundation',
                   'Concealer',
                   'Phấn phủ',
                   'Setting powder',
                   'Mặt nạ đất sét (clay mask)',
                   'Scrub (tẩy da chết)',
                   'Bùn khoáng'],
    'nghe_thuat': [   'Gốm sứ Bát Tràng',
                      'Pottery art',
                      'Điêu khắc đá',
                      'Sand art (tranh cát)',
                      'Mosaic art',
                      'Terrazzo art',
                      'Tạc tượng',
                      'Tranh gạch ceramic'],
    'nhac_cu': [   'Trống đất (udu drum)',
                   'Ocarina',
                   'Cồng chiêng',
                   'Trống đồng Đông Sơn',
                   'Djembe (gỗ+da)',
                   'Tabla',
                   'Xylophone',
                   'Marimba',
                   'Lithophone (đàn đá)',
                   'Didgeridoo'],
    'noi_that': [   'Tường gạch trần',
                    'Sàn gạch',
                    'Bàn đá marble',
                    'Bếp đá granite',
                    'Chậu sứ',
                    'Bình gốm',
                    'Tượng trang trí đá',
                    'Gạch mosaic',
                    'Sàn đá hoa',
                    'Kệ gạch xây',
                    'Bồn cầu sứ',
                    'Bồn rửa đá'],
    'nong_nghiep': [   'Cày bừa',
                       'San lấp đất',
                       'Đào ao',
                       'Đắp đê',
                       'Bón phân',
                       'Ủ phân compost',
                       'Hệ thống thoát nước ruộng',
                       'Gieo hạt trực tiếp',
                       'Trồng khoai',
                       'Trồng ngô',
                       'Nuôi giun đất',
                       'Trại nấm'],
    'phuong_tien': {   'Lâm Quan': ['Xe tải Howo', 'Xe ben Kamaz', 'Xe lu Dynapac'],
                       'Suy': ['Xe tải cũ', 'Xe ủi hỏng', 'Xe ben rỉ sét'],
                       'chung': ['Xe tải', 'Xe ben', 'Xe ủi', 'Xe xúc', 'Xe lu', 'Xe cẩu', 'Xe trộn bê tông'],
                       'Đế Vượng': ['Xe đào siêu lớn', 'Cẩu bánh xích khổng lồ', 'Máy xúc CAT lớn nhất']},
    'quoc_gia': [   'Trung Quốc (đại lục)',
                    'Ai Cập (kim tự tháp)',
                    'Peru (Machu Picchu)',
                    'Ấn Độ (Taj Mahal)',
                    'Campuchia (Angkor Wat)',
                    'Rome (Colosseum)',
                    'Đồng bằng sông Cửu Long',
                    'Tây Nguyên'],
    'the_thao': [   'Đấu vật sumo',
                    'Judo',
                    'Wrestling',
                    'Cử tạ',
                    'Strongman',
                    'Leo núi',
                    'Hiking',
                    'Golf (trên cỏ/đất)',
                    'Bóng đá (sân đất)',
                    'Xe đạp địa hình MTB',
                    'Motocross (đất)'],
    'thoi_tiet': [   'Động đất',
                     'Núi lửa phun',
                     'Sạt lở đất',
                     'Bụi cát sa mạc',
                     'Thời tiết nóng ẩm cuối hạ',
                     'Giao mùa',
                     'Oi bức'],
    'thuc_pham_chi_tiet': {   'chung': [   'Khoai lang',
                                           'Khoai tây',
                                           'Khoai môn',
                                           'Khoai sọ',
                                           'Sắn',
                                           'Dong',
                                           'Cơm trắng',
                                           'Bánh mì',
                                           'Bánh bao',
                                           'Mantou',
                                           'Naan',
                                           'Tortilla',
                                           'Phở',
                                           'Bún',
                                           'Miến',
                                           'Cháo',
                                           'Xôi',
                                           'Đường',
                                           'Mật ong',
                                           'Mật mía',
                                           'Bánh ngọt',
                                           'Bánh trung thu',
                                           'Bí đỏ',
                                           'Bí ngô',
                                           'Ngô ngọt',
                                           'Lạc (đậu phộng)',
                                           'Khoai lang mật',
                                           'Nấm hương',
                                           'Nấm rơm',
                                           'Nấm đùi gà',
                                           'Nấm linh chi',
                                           'Nấm truffle'],
                              'do_uong': [   'Sữa đậu nành',
                                             'Nước mía',
                                             'Trà sữa trân châu',
                                             'Rượu nếp',
                                             'Rượu đế',
                                             'Mật ong pha nước',
                                             'Smoothie chuối']},
    'ton_giao': [   'Tượng Phật đá',
                    'Đền đài',
                    'Chùa/nhà thờ (bê tông/đá)',
                    'Mộ phần',
                    'Lăng tẩm',
                    'Kim tự tháp',
                    'Bàn thờ đá',
                    'Bia đá khắc',
                    'Bùa đất',
                    'Tháp Chàm',
                    'Stonehenge',
                    'Angkor Wat',
                    'Đền Parthenon'],
    'trang_phuc': {   'Mộ': ['Đồ tang lễ', 'Áo xá (nhà sư)', 'Y phục cổ xưa'],
                      'Suy': ['Áo bảo hộ cũ', 'Quần kaki rách', 'Ủng nứt'],
                      'chung': [   'Áo nâu (nhà sư)',
                                   'Quần kaki',
                                   'Đồ bảo hộ lao động',
                                   'Ủng xây dựng',
                                   'Nón bảo hộ vàng',
                                   'Găng tay vải',
                                   'Yếm',
                                   'Áo chống nắng nâu'],
                      'Đế Vượng': ['Áo gấm vàng', 'Long bào (áo vua)', 'Trang phục hoàng gia màu vàng']},
    'van_phong': [   'Chặn giấy đá',
                     'Ly sứ uống trà',
                     'Chậu cây văn phòng',
                     'Pot cây sen đá',
                     'Máy pha cà phê (gốm)',
                     'Art ceramic trang trí bàn',
                     'Đĩa đựng card'],
    'y_te': [   'Bó bột (xương gãy)',
                'Đắp bùn khoáng',
                'Tắm bùn trị liệu',
                'Thuốc chống dạ dày (antacid)',
                'Thuốc dạ dày Gaviscon',
                'Thuốc tiêu hóa',
                'Probiotic đường ruột',
                'Viên sắt bổ máu',
                'Canxi (xương)',
                'Thạch cao bó bột',
                'Đất sét trị liệu',
                'Bùn nóng onsen']}
